# Change these first
owner: nacionvirtualchile # Your GitHub organization or username, where this repository lives
repo: WebMonitor # The name of this repository

sites:
  - name: NacionVirtual.cl
    url: https://www.nacionvirtual.cl
  - name: FMN.cl
    url: https://www.fmn.cl
  - name: Parapenteantofagasta
    url: https://parapenteantofagasta.cl
  - name: Ecoshower.cl
    url: https://ecoshower.cl


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: https://nacionvirtualchile.github.io/WebMonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: WebMonitor
  introTitle: "**Monitor Web** de Nacionvirtual.cl."
  introMessage: Aquí estará el status de los siguientes sitios. Open source tool. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
